# Generated by Django 4.1.3 on 2022-11-03 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billetera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_billetera', models.CharField(max_length=40)),
                ('fecha_creacion', models.DateTimeField(verbose_name='date published')),
                ('total_dinero', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_ingreso', models.CharField(max_length=100)),
                ('valor', models.FloatField(default=0)),
                ('billetera_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billetera.billetera')),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_gasto', models.CharField(max_length=100)),
                ('valor', models.FloatField(default=0)),
                ('billetera_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billetera.billetera')),
            ],
        ),
    ]
