# Generated by Django 4.1.3 on 2022-11-22 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billetera', '0002_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='categoria_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='billetera.categoria'),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='categoria_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='billetera.categoria'),
        ),
    ]
