# Generated by Django 4.1.3 on 2022-11-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billetera', '0004_alter_gasto_categoria_id_alter_ingreso_categoria_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='tipo_categoria',
            field=models.CharField(default='ingreso', max_length=30),
            preserve_default=False,
        ),
    ]
