# Generated by Django 4.1.3 on 2022-12-01 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billetera', '0005_categoria_tipo_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gasto',
            old_name='descripcion_gasto',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='ingreso',
            old_name='descripcion_ingreso',
            new_name='descripcion',
        ),
    ]
