# Generated by Django 4.1.3 on 2022-12-07 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ahorros', '0004_initial'),
        ('billetera', '0009_remove_billetera_ahorro_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='billetera',
            name='ahorro_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ahorros.ahorro'),
        ),
    ]
