# Generated by Django 4.1.3 on 2022-12-20 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ahorros', '0006_inversion_roi_inversion_fecha_creacion'),
        ('billetera', '0010_billetera_ahorro_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billetera',
            name='ahorro_id',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='ahorros.ahorro'),
        ),
    ]
