# Generated by Django 4.1.3 on 2022-12-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahorros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahorro',
            name='cantidad_dinero',
            field=models.FloatField(),
        ),
    ]
