# Generated by Django 4.1.3 on 2022-12-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahorros', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inversion',
            name='valor_inversion',
            field=models.FloatField(default=0),
        ),
    ]
