# Generated by Django 4.1.3 on 2022-12-20 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahorros', '0006_inversion_roi_inversion_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inversion',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 20, 20, 37, 59, 85956, tzinfo=datetime.timezone.utc)),
        ),
    ]
