# Generated by Django 4.1.3 on 2022-12-28 01:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahorros', '0007_alter_inversion_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inversion',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 28, 1, 37, 2, 491021, tzinfo=datetime.timezone.utc)),
        ),
    ]
