# Generated by Django 4.1.3 on 2023-01-05 23:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ahorros', '0008_alter_inversion_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ahorro',
            name='usuario_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inversion',
            name='usuario_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inversion',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 5, 23, 45, 39, 150960, tzinfo=datetime.timezone.utc)),
        ),
    ]
